#baseUrl: http://51.75.242.129:8079/api
baseUrl: http://localhost:8090/api

checkAppRegistrationUrl: ${baseUrl}/tokens/signup/check-scanner
registrationUrl: ${baseUrl}/tokens/signup/scanner

scannedItemsUrl: ${baseUrl}/check-scan
revertScannedItemsUrl: ${baseUrl}/check-scan/revert

requestLoginUrl: ${baseUrl}/tokens/signin/scanner/request
requestLoginUsersUrl: ${baseUrl}/tokens/signin/scanner/users
loginUrl: ${baseUrl}/tokens/signin/scanner

pageItems: 17
loginTokenCountdown: 300

scanStoragePath: C:\Users\Seydou.Sow\IdeaProjects\cdc-scanner\src\main\resources\model-scan
scanArchivePath: C:\Users\Seydou.Sow\IdeaProjects\cdc-scanner\src\main\resources\archive
