baseUrl: http://localhost:8090/api

checkAppRegistrationUrl: ${baseUrl}/tokens/signup/check-scanner
registrationUrl: ${baseUrl}/tokens/signup/scanner

listScannedItemsUrl: ${baseUrl}/check-scan

requestLoginUrl: ${baseUrl}/tokens/signin/scanner/request
requestLoginUsersUrl: ${baseUrl}/tokens/signin/scanner/users
loginUrl:  ${baseUrl}/tokens/signin/scanner

pageItems: 17
loginTokenCountdown: 300
